# SPDX-FileCopyrightText: 2021-2022 Alliander N.V.
#
# SPDX-License-Identifier: MPL-2.0
version: 2

updates:
  # -------- Gradle dependencies --------
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # -------- Docker images --------
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
