// SPDX-FileCopyrightText: 2021-2022 Alliander N.V.
//
// SPDX-License-Identifier: MPL-2.0

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.alliander.open.measure.generator

class AppTest {
/*
 * Intentionally left blank
 */
}
